            - name: Reload pythonanywhere webapp
  # You may pin to the exact commit or the version.
  # uses: jensvog/pythonanywhere-webapp-reload-action@6d0dda613f7caccecc8bee5695813b2ecb1a667d
  uses: jensvog/pythonanywhere-webapp-reload-action@v1
  with:
    # Pythonanywhere host (EU/US), can be either eu.pythonanywhere.com or www.pythonanywhere.com (default)
    host: # optional, default is www.pythonanyhwere.com
    # Username for pythonanywhere
    username:
    # API token for pythonanywhere
    api-token: 
    # Domain name of the webapp to reload
    domain-name: https://supernoob20.pythonanywhere.com/
          
